//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSClock.Languages.Swedish {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configure {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configure() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSClock.Languages.Swedish.Configure", typeof(Configure).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkställ.
        /// </summary>
        internal static string button_apply_text {
            get {
                return ResourceManager.GetString("button_apply_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisk uppdaterare är installerad.
        /// </summary>
        internal static string button_dwnldAutoUpdater_done_text {
            get {
                return ResourceManager.GetString("button_dwnldAutoUpdater_done_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hämta automatisk uppdaterare (rekommenderas).
        /// </summary>
        internal static string button_dwnldAutoUpdater_notdone_text {
            get {
                return ResourceManager.GetString("button_dwnldAutoUpdater_notdone_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mindre ↑.
        /// </summary>
        internal static string button_moreless_text__less {
            get {
                return ResourceManager.GetString("button_moreless_text__less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mer ↓.
        /// </summary>
        internal static string button_moreless_text__more {
            get {
                return ResourceManager.GetString("button_moreless_text__more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tar bort all data från CSClock för denna användare.
        /// </summary>
        internal static string button_remove_toolTip {
            get {
                return ResourceManager.GetString("button_remove_toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Återställ.
        /// </summary>
        internal static string button_reset_text {
            get {
                return ResourceManager.GetString("button_reset_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra språk.
        /// </summary>
        internal static string button_selectLanguage_toolTip {
            get {
                return ResourceManager.GetString("button_selectLanguage_toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivera timer (rekommenderas).
        /// </summary>
        internal static string checkBox_enableTimer_text {
            get {
                return ResourceManager.GetString("checkBox_enableTimer_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa GUI-fönstret över de andra fönsterna.
        /// </summary>
        internal static string checkBox_guiTopMost_text {
            get {
                return ResourceManager.GetString("checkBox_guiTopMost_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausa/återuppta timern när datorn låses/låses upp (rekommenderas).
        /// </summary>
        internal static string checkBox_pauseResumeTimerOnComputerLockUnlock_text {
            get {
                return ResourceManager.GetString("checkBox_pauseResumeTimerOnComputerLockUnlock_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starta CSClock med Windows (rekommenderas).
        /// </summary>
        internal static string checkBox_startCSClockWithWindows_text {
            get {
                return ResourceManager.GetString("checkBox_startCSClockWithWindows_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSClock - Konfiguration.
        /// </summary>
        internal static string form_title {
            get {
                return ResourceManager.GetString("form_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fre.
        /// </summary>
        internal static string l_fri_text {
            get {
                return ResourceManager.GetString("l_fri_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mån.
        /// </summary>
        internal static string l_mon_text {
            get {
                return ResourceManager.GetString("l_mon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lör.
        /// </summary>
        internal static string l_sat_text {
            get {
                return ResourceManager.GetString("l_sat_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sön.
        /// </summary>
        internal static string l_sun_text {
            get {
                return ResourceManager.GetString("l_sun_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tor.
        /// </summary>
        internal static string l_thu_text {
            get {
                return ResourceManager.GetString("l_thu_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tis.
        /// </summary>
        internal static string l_tue_text {
            get {
                return ResourceManager.GetString("l_tue_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ons.
        /// </summary>
        internal static string l_wed_text {
            get {
                return ResourceManager.GetString("l_wed_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximalt antal timmar tillåtna
        ///(sätt till 0 för att inaktivera begränsning).
        /// </summary>
        internal static string label1_text {
            get {
                return ResourceManager.GetString("label1_text", resourceCulture);
            }
        }
    }
}
