/*
PCTime - a program which keeps track of your computer time
Copyright (C) 2017  Viktor J

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTime.Languages.English {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCTime.Languages.English.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will be used.
        /// </summary>
        internal static string changeLang_confirm_msg {
            get {
                return ResourceManager.GetString("changeLang_confirm_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCTime will be minimized to the taskbar and the timer will continue to run. If you would like to quit PCTime completely, please use the &quot;Quit&quot; button in the application user interface/the &quot;Quit&quot; button in the tray icon.
        /// </summary>
        internal static string closeNotice {
            get {
                return ResourceManager.GetString("closeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCTime will be minimized to the taskbar and will continue to run. If you would like to quit PCTime completely, please use the &quot;Quit&quot; button in the application user interface/the &quot;Quit&quot; button in the tray icon.
        /// </summary>
        internal static string closeNotice_v2 {
            get {
                return ResourceManager.GetString("closeNotice_v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT RUNNING.
        /// </summary>
        internal static string NOT_RUNNING {
            get {
                return ResourceManager.GetString("NOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you don&apos;t want to enable the timer? PCTime won&apos;t keep track of your computer time if it&apos;s not enabled.
        /// </summary>
        internal static string notEnableTimerConfirmation_text {
            get {
                return ResourceManager.GetString("notEnableTimerConfirmation_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCTime
        ///
        ///Timer is {0}
        ///Time remaining: {1}.
        /// </summary>
        internal static string notifyIcon_text {
            get {
                return ResourceManager.GetString("notifyIcon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCTime DEBUG
        ///
        ///Timer is {0}
        ///Time remaining: {1}.
        /// </summary>
        internal static string notifyIcon_text_debug {
            get {
                return ResourceManager.GetString("notifyIcon_text_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your overtime of your computer time is out!.
        /// </summary>
        internal static string overtimeIsOutNotification_text {
            get {
                return ResourceManager.GetString("overtimeIsOutNotification_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAUSED.
        /// </summary>
        internal static string PAUSED {
            get {
                return ResourceManager.GetString("PAUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCTime continues to run in the background.
        /// </summary>
        internal static string PCTimeContinuesToRunInTheBackgroundNotification_text {
            get {
                return ResourceManager.GetString("PCTimeContinuesToRunInTheBackgroundNotification_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit PCTime completely? This will stop the timer.
        /// </summary>
        internal static string quitConfirmationDialog_text {
            get {
                return ResourceManager.GetString("quitConfirmationDialog_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove PCTime from this user? This will also remove the user data and logs of PCTime.
        /// </summary>
        internal static string removalQuestion {
            get {
                return ResourceManager.GetString("removalQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset PCTime? PCTime will exit if you do so.
        /// </summary>
        internal static string resetConfirmation {
            get {
                return ResourceManager.GetString("resetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUNNING.
        /// </summary>
        internal static string RUNNING {
            get {
                return ResourceManager.GetString("RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutes remains of your computer time.
        /// </summary>
        internal static string tenMinutesRemainingNotification_text {
            get {
                return ResourceManager.GetString("tenMinutesRemainingNotification_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer time is out! Click here to set and allow overtime.
        /// </summary>
        internal static string timeIsOutNotification_text {
            get {
                return ResourceManager.GetString("timeIsOutNotification_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer has been paused.
        /// </summary>
        internal static string timerPausedNotification_text {
            get {
                return ResourceManager.GetString("timerPausedNotification_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer has been resumed.
        /// </summary>
        internal static string timerResumedNotification_text {
            get {
                return ResourceManager.GetString("timerResumedNotification_text", resourceCulture);
            }
        }
    }
}
