/*
PCTime - a program which keeps track of your computer time
Copyright (C) 2017  Viktor J

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTime.Languages.Swedish {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCTime.Languages.Swedish.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kommer användas/will be used.
        /// </summary>
        internal static string changeLang_confirm_msg {
            get {
                return ResourceManager.GetString("changeLang_confirm_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCTime kommer att minimeras till aktivitetsfältet och timern kommer fortsätta att köra. Om du vill avsluta PCTime helt, vänligen använd &quot;Avsluta&quot;-knappen i användargränssnittet/&quot;Avsluta&quot;-knappen i ikonen i aktivitetsfältet.
        /// </summary>
        internal static string closeNotice {
            get {
                return ResourceManager.GetString("closeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCTime kommer att minimeras till aktivitetsfältet och fortsätta att köras. Om du vill avsluta PCTime helt, vänligen använd &quot;Avsluta&quot;-knappen i användargränssnittet/&quot;Avsluta&quot;-knappen i ikonen i aktivitetsfältet.
        /// </summary>
        internal static string closeNotice_v2 {
            get {
                return ResourceManager.GetString("closeNotice_v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EJ IGÅNG.
        /// </summary>
        internal static string NOT_RUNNING {
            get {
                return ResourceManager.GetString("NOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du inte vill aktivera timern? PCTime kommer inte att hålla koll på din datortid om den inte är aktiverad.
        /// </summary>
        internal static string notEnableTimerConfirmation_text {
            get {
                return ResourceManager.GetString("notEnableTimerConfirmation_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCTime
        ///
        ///Timern är {0}
        ///Återstående tid: {1}.
        /// </summary>
        internal static string notifyIcon_text {
            get {
                return ResourceManager.GetString("notifyIcon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCTime DEBUG
        ///
        ///Timer is {0}
        ///Time remaining: {1}.
        /// </summary>
        internal static string notifyIcon_text_debug {
            get {
                return ResourceManager.GetString("notifyIcon_text_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din övertid av din datortid är slut!.
        /// </summary>
        internal static string overtimeIsOutNotification_text {
            get {
                return ResourceManager.GetString("overtimeIsOutNotification_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAUSAD.
        /// </summary>
        internal static string PAUSED {
            get {
                return ResourceManager.GetString("PAUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCTime fortsätter att köras i bakgrunden.
        /// </summary>
        internal static string PCTimeContinuesToRunInTheBackgroundNotification_text {
            get {
                return ResourceManager.GetString("PCTimeContinuesToRunInTheBackgroundNotification_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill avsluta PCTime helt? Timern kommer att stoppas.
        /// </summary>
        internal static string quitConfirmationDialog_text {
            get {
                return ResourceManager.GetString("quitConfirmationDialog_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort PCTime från denna användare? All användardata och alla loggar kommer även att tas bort.
        /// </summary>
        internal static string removalQuestion {
            get {
                return ResourceManager.GetString("removalQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill nollställa PCTime? PCTime kommer att stängas om du gör det.
        /// </summary>
        internal static string resetConfirmation {
            get {
                return ResourceManager.GetString("resetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGÅNG.
        /// </summary>
        internal static string RUNNING {
            get {
                return ResourceManager.GetString("RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minuter återstår av din datortid.
        /// </summary>
        internal static string tenMinutesRemainingNotification_text {
            get {
                return ResourceManager.GetString("tenMinutesRemainingNotification_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din datortid är slut! Klicka här för att ställa in och tillåta övertid.
        /// </summary>
        internal static string timeIsOutNotification_text {
            get {
                return ResourceManager.GetString("timeIsOutNotification_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timern has pausats.
        /// </summary>
        internal static string timerPausedNotification_text {
            get {
                return ResourceManager.GetString("timerPausedNotification_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timern har återupptagits.
        /// </summary>
        internal static string timerResumedNotification_text {
            get {
                return ResourceManager.GetString("timerResumedNotification_text", resourceCulture);
            }
        }
    }
}
